- README.md
- radar.csv
- smaller-context.csv
> Choose rings

- radar.csv
See #20 and preview [here](https://radar.thoughtworks.com/?sheetId=https%3A%2F%2Fraw.githubusercontent.com%2Fred-gate%2FTech-Radar%2F39c342a587708d8cc03600d4d51925300d947f52%2Fradar.csv)
> Update with supported browsers.

- radar.csv
See #34 
Preview of this commit in radar form [here](https://radar.thoughtworks.com/?sheetId=https%3A%2F%2Fraw.githubusercontent.com%2Fred-gate%2FTech-Radar%2F96d6cac80ad8925692f101af7301ce71d2d7370c%2Fradar.csv)
> Retire RavenDB

- radar.csv
- smaller-context.csv
> Add ADR to Techniques:Adopt

- radar.csv
> express our stand on IoC containers inside the radar

- README.md
Resolves #44, if @fffej agrees with it.
(No radar change, so no preview.)
> Clarify expectations of Adopt

- radar.csv
Resolves #17:
Adopt: RedGate.Usage.Client
Adopt: AppInsights
Retire: MixPanel
Retire: Google Analytics
Updates text for Smart Assembly to include feature usage reporting.
[Radar update](https://radar.thoughtworks.com/?sheetId=https://raw.githubusercontent.com/red-gate/Tech-Radar/9cfaacbfe1865c7d0f27ce46bec8355f1343f93e/radar.csv)
> Add Feature Usage tools

- radar.csv
Resolves #19:
Adopt: Wix 3
Retire: Wix 2
Endure: Inno Setup
[Radar update](https://radar.thoughtworks.com/?sheetId=https://raw.githubusercontent.com/red-gate/Tech-Radar/a188dfd21ab713982ff98b2649ad85419f65efc5/radar.csv)
> Add installer tech

- README.md
> Update README with commitment and accountability

- README.md
> Scope of Tech Radar

- radar.csv
> Update TS and JS ES6+ to Adopt, JS pre ES6 to Retire

- radar.csv
Resolves #18 
[Render](https://radar.thoughtworks.com/?sheetId=https://raw.githubusercontent.com/red-gate/Tech-Radar/f696342356c5389072256ed55c2f4fdbecdfe9ef/radar.csv)
I'm not _convinced_ this should be in tools, but nowhere else feels better.
> Add CfU and SQL Clone update mechanisms

- radar.csv
Resolves #23 
[Preview](https://radar.thoughtworks.com/?sheetId=https://raw.githubusercontent.com/red-gate/Tech-Radar/6fd057777273d89446a41da1310e1ca488183ba1/radar.csv)
> Add desktop UI frameworks

- .gitattributes
This will hopefully reduce the number of merge conflicts as items are added to the radar.
[Relevant git documentation for context](https://git-scm.com/docs/gitattributes)
> Use union merge on radar.csv

- radar.csv
Resolves #16 (or at least part of it).
[Preview](https://radar.thoughtworks.com/?sheetId=https%3A%2F%2Fraw.githubusercontent.com%2Fred-gate%2FTech-Radar%2F60f72a38ce74b288a215898d6afa13bfe1e26add%2Fradar.csv)
> Update with web UI stuff.

- radar.csv
> Release management

- README.md
This link currently only works internally, but it will work externally soon.
> Give a nice link

- README.md
As mentioned in #16 discussion.
> Add FAQ section, with first bit on micro-libraries

- .github/CONTRIBUTING.md
- .github/ISSUE_TEMPLATE.md
- .github/PULL_REQUEST_TEMPLATE.md
I thought this may be useful as people open more PRs going forward.
Content is my initial stab, and is pretty open for improvement!
> Add contributing.md

- .github/PULL_REQUEST_TEMPLATE.md
Cleans up the PR template - I messed up the markdown for the checkboxes!
> Fix checkboxes in PR template

- radar.csv
> Add Redgate Installer to Adopt

- radar.csv
> Add prettier to Adopt

- radar.csv
> Add TeamCity to Adopt

- radar.csv
> Update with positions for PowerShell

- .github/PULL_REQUEST_TEMPLATE.md
> We expect new/updated radar entries to be marked as new

- radar_libraries.csv
> Summarise current JS utility recommendations

- README.md
Adding some documentation on why we have a separate libraries radar as per #197 
- ~[ ] Are all new or updated entries marked as `isNew` = `true`?~
- ~[ ] Does `radar.csv` render correctly when viewed on Github?~
- ~[ ] Does the [updated tech radar](https://radar.thoughtworks.com/?sheetId=https%3A%2F%2Fraw.githubusercontent.com%2Fred-gate%2FTech-Radar%2F +++ ADD YOUR BRANCH NAME HERE +++  %2Fradar.csv) display as you expect?~
> Update README.md re `radar_libraries.csv`

- radar.csv
> Remove Fody

- radar.csv
Endure IE 11 (Internet Explorer 11, IE11).
Discussion: https://redgate.slack.com/archives/C7E87T0VA/p1556194553006800
> Endure IE 11

- radar.csv
Resolves #262 
I haven't marked the JSON entry as `isNew`. Since this is tidying up the radar, rather than recording any meaningful change, I don't think it should be highlighted as `isNew` for people viewing the radar.
Happy to be convinced otherwise.
> Move JSON to 'Languages and frameworks'

- README.md
> Clarify intent of the Adopt ring

- radar_libraries.csv
> add Monaco Editor to explore for libraries

- radar.csv
> Remove RavenDB - we don't believe anyone will make that choice aagain.

- radar.csv
> Octopus Deploy is a tool

- README.md
> Update readme to clarify how to contribute

- radar.csv
> Retire Raygun

- radar.csv
> Fix URL to progression.red-gate.com

- radar.csv
> Add the gitops tool  an technique that platform is currently using as trial items

- radar.csv
> Add ORMs to Languages and Frameworks

- radar.csv
> Add Python to trial.

- README.md
~- [ ] Are all new or updated entries marked as `isNew` = `true`?~
~- [ ] Does `radar.csv` render correctly when viewed on Github?~
~- [ ] Does the updated [tech radar](https://radar.thoughtworks.com/?sheetId=https%3A%2F%2Fraw.githubusercontent.com%2Fred-gate%2FTech-Radar%2Fclarify-areas%2Fradar.csv) display as you expect?~
> Clarify the 4 areas

- radar.csv
> Update radar.csv to include RestSharp

- radar.csv
> Move Circle CI to Adopt

- radar.csv
> Go - Move to Hold

- radar.csv
> Adopt OpenTelemetry
